name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '15 9 * * *'

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      # versions: ["debug"]
      min_version: 3.3

  host:
    needs: ruby-versions
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-22.04
        - windows-latest
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        include:
        - { os: windows-latest, ruby: ucrt }
        - { os: windows-latest, ruby: mswin }
        exclude:
        - { os: windows-latest, ruby: debug }
        - { os: windows-latest, ruby: head }

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # 'bundle install' and cache

      - run: ruby --version

      - run: bundle exec rake compile

      - run: bundle exec rake build

      - run: bundle exec rake test
        continue-on-error: ${{ matrix.ignore-error }}

      - name: Integration test
        run: bundle exec rake check
        continue-on-error: >-
          ${{
          matrix.ignore-pkg-error ||
          (matrix.ruby == 'debug') ||
          false }}
